### ISSUE TITLE
[Feature Request] Android port?

### ISSUE THREAD

**Issue by austinarchibald** [TheFlyingFoool/DuckGameRebuilt#44]
Any chance of an Android port? Been running the ouya version from archive.org, but would prefer this if possible! Thanks.

**Comment by klof44** [comment]
There was a almost functional android version but it was abandoned. If someone were to show interest in working on an android version we would not be opposed but it is not being worked on currently.

**Comment by athyfr** [comment]
Sorry for the necroposting, but @klof44, could you link the abandoned Android port? I'm interesting in looking at the code.

**Comment by erik7302** [comment]
> Sorry for the necroposting, but [@klof44](https://github.com/klof44), could you link the abandoned Android port? I'm interesting in looking at the code.

Hi i am the guy that made the Android port, here it is in this branch https://github.com/TheFlyingFoool/DuckGameRebuilt/tree/DGRA
it was abandoned bcz Fna android fork i used was full of bugs.
Do you have discord? i am on this project discord if u have any questions regarding the android port.
