### ISSUE TITLE
Chat gets squished on non-16:9 during fixed camera

### ISSUE THREAD

**Issue by othello777** [TheFlyingFoool/DuckGameRebuilt#49]
I know this at least happens on the intermission on ultrawide. it theoretically is also happening on all fixed camera maps on all non-16:9 monitors I would think. it's just the chat. everything else scales fine and correctly is boxed in to 16:9
![image](https://github.com/TheFlyingFoool/DuckGameRebuilt/assets/34588890/6f0fa1a1-657a-48d5-95bd-fef2fd57f76c)

**Comment by sjrc6** [comment]
fixed by https://github.com/TheFlyingFoool/DuckGameRebuilt/commit/2b348b4cb4d9123100efa1b71c1823c956cc3e03
